export const questions1 = [
  "Apresenta a verdade de maneira lógica e sistemática",
  "Guarda recursos financeiros para gerações futuras (ex.: filhos, netos, etc.)",
  "É altamente motivado para organizar e implementar planos",
  "É capaz de ter desentendimentos significativos sem ofender",
  "Tem uma tremenda capacidade de mostrar amor",
  "Identifica o certo rapidamente e com precisão",
  "Reconhece necessidades práticas e é rápido para atendê-las",
  "Valida a verdade confrontando-a com os fatos",
  "É capaz de aceitar pessoas com diversos pontos de vista",
  "Prefere estar sob autoridade para ter autoridade",
  "Evita ficar sozinho",
  "Sente a atmosfera emocional de um grupo/indivíduo",
  "Vê tudo como preto ou branco",
  "Gosta de mostrar hospitalidade",
  "Gosta de estudar e pesquisar",
  "Gosta de manter todas as opções abertas o maior tempo possível",
  "Suporta críticas para realizar a tarefa",
  "Relaciona-se com pessoas independentemente da cultura, raça, religião, origem, etc.",
  "Evita conflitos e confrontos",
  "Percebe facilmente o caráter de indivíduos ou grupos",
  "Permanece em algo até que esteja completo",
  "Enfatiza fatos e precisão das palavras",
  "Lida com todas as situações como uma situação única",
  "É hábil no gerenciamento do tempo",
  "Ama encorajar os outros a viverem vitoriosamente",
  "É atraído por pessoas que estão sofrendo ou angustiadas",
  "Trabalha a partir de princípios",
  "Acha difícil dizer 'não' aos pedidos de ajuda",
  "Resolve problemas começando com uma fundamentação teórica",
  "Tende a ser mais relativo do que absoluto",
  "Facilita recursos e pessoas para realizar tarefas ou alcançar objetivos",
  "Quer uma resposta visível ao ensinar ou falar",
  "Detecta facilmente falta de sinceridade ou motivações erradas",
  "Anseia por ver os seus próprios pontos cegos e ajudar os outros a verem os seus também",
  "Tem necessidade de ser apreciado",
  "Pega coisas emprestadas (ex.: livros) e não as devolve rapidamente",
  "Vê a família como importante",
  "Prefere seguir para um novo desafio quando algo é concluído",
  "É muito amado por causa da atitude positiva",
  "É cuidadoso com palavras e ações para evitar ferir os outros",
  "Sente necessidade de verbalizar ou dramatizar o que percebe",
  "Sente grande alegria em fazer algo que seja útil",
  "Tem fortes convicções e opiniões baseadas na investigação de fatos",
  "É preocupado com a comunidade",
  "Obtém sucesso sob estresse/pressão",
  "Vê provações como oportunidades para produzir crescimento pessoal",
  "É governado pelo coração e não pela cabeça",
  "Tem opiniões e convicções fortes",
  "Evita liderar outras pessoas ou projetos",
  "Gosta muito de escrever",
  "Vê dinheiro como segurança",
  "Quer ver as coisas concluídas o mais rápido possível",
  "Acha fácil se comunicar com os outros",
  "Percebe as coisas sem saber explicar 'como'",
  "É franco, sincero e não mede palavras",
  "Apoia aqueles que estão na liderança",
  "Tende a usar ilustrações bíblicas em vez de ilustrações da vida",
  "Dá livremente bens/tempo/amor, mas sempre quer o melhor",
  "Gosta de projetos de longo prazo e não gosta de rotina",
  "Prefere aplicar a verdade em vez de pesquisá-la",
  "Alegra-se quando os outros são abençoados, se aflige quando são feridos",
  "Acredita que a tribulação produz quebrantamento/humildade",
  "Está mais interessado em satisfazer as necessidades dos outros do que nas próprias necessidades",
  "Fica chateado se as Escrituras são usadas fora do contexto",
  "Dá sem que outras pessoas saibam disso",
  "Pode facilmente delegar tarefas e supervisionar os outros",
  "Quer dar às pessoas instruções específicas sobre 'como fazer'",
  "Não gosta de ser apressado",
  "Acredita que o verdadeiro arrependimento será evidenciado por bons frutos",
  "Trabalha com metas imediatas em vez de objetivos de longo prazo",
  "É autodisciplinado e autocontrolado",
  "Tem uma forte crença no dízimo/oferta de primícias",
  "Está disposto a deixar que os outros ganhem crédito para fazer o trabalho",
  "Gosta de fazer aconselhamento pessoal, mas para se não for visto nenhum esforço para mudar",
  "Tipicamente evita conflitos/confrontos",
  "Tende a ter apenas um ou dois amigos próximos e tende a ser introspectivo",
  "Mostra amor mais em atitudes do que em palavras",
  "Acredita que a verdade tem o poder de mudança",
  "Não é ingênuo/facilmente enganado.",
  "Está sempre escrevendo notas para si mesmo",
  "Espera muito dos outros",
  "Ama fazer coisas pensando nos outros",
  "Sabe que é chamado para ser um intercessor",
  "Tende a fazer o trabalho em vez de delegar",
  "Tem um círculo seleto de amigos com base em interesses comuns",
  "Gosta de ver o valor das coisas que o dinheiro compra",
  "Sabe quando deve continuar fazendo as coisas da maneira antiga e quando deve apresentar novas ideias",
  "Precisa ter alguém como uma 'caixa de ressonância' para ouvir ideias/conceitos",
  "É mais preocupado com estresse mental/emocional do que com desconforto físico",
  "Tem um desejo fervoroso de ver o plano de Deus se manifestar em todas as situações",
  "Tem um alto nível de energia",
];

export const questions2 = [
  "Eu sou cuidadoso com o dinheiro e oro continuamente por sua distribuição adequada na obra do Senhor.",
  "Eu gosto de desenvolver maneiras de apresentar materiais que ajudem os outros a aprenderem mais facilmente.",
  "Facilmente delego tarefas para os outros.",
  "Eu me sinto feliz por ajudar alguém que está desanimado.",
  "Eu me sinto mais confortável recebendo ordens do que dando-as.",
  "Eu amo encorajar os outros a viverem vitoriosamente.",
  "Eu tenho consciência da presença de espíritos malignos em certas pessoas, lugares e coisas.",
  "Eu vejo a hospitalidade como uma oportunidade para doar.",
  "Eu gosto de explicar o que algo significa.",
  "Eu gosto mais de projetos de longo prazo (6 meses - 5 anos) do que projetos de curto prazo (1 dia - 2 semanas).",
  "Eu sou guiado pelo meu coração e não pela minha cabeça.",
  "Eu sinto grande alegria quando ajudo aqueles que estão em necessidade.",
  "Eu amo fazer aconselhamento pessoal.",
  "Eu rapidamente e com precisão identifico o bem e o mal - e odeio o mal.",
  "Eu sou capaz de administrar meus assuntos financeiros eficientemente para que eu possa doar generosamente para a obra do Senhor.",
  "Eu amo ver a luz do entendimento acendendo em outra pessoa.",
  "Eu sou capaz de estabelecer metas e fazer planos eficazes para alcançá-las.",
  "Eu prontamente simpatizo com as desgraças dos outros.",
  "Eu prefiro fazer as coisas sozinho do que delegar.",
  "Eu geralmente começo usando a experiência quando tento encontrar soluções para problemas.",
  "Eu sofro profundamente com os pecados dos outros, assim como com os meus.",
  "Tenho o anseio de compartilhar o Evangelho.",
  "Eu fico chateado quando as Escrituras são usadas fora de contexto.",
  "Desejo que haja harmonia em uma organização para que ela funcione bem.",
  "Tenho uma grande preocupação com aqueles que estão passando por problemas.",
  "Eu gosto de tirar as cargas de pessoas-chave para que elas possam dar mais atenção suas tarefas pessoais.",
  "Eu gosto de dar às pessoas instruções precisas para realizarem as ações.",
  "Eu vejo tudo como preto ou branco; certo ou errado, sem áreas cinzentas.",
  "Às vezes eu me percebo querendo controlar como o dinheiro que eu dou é usado.",
  "Tenho prazer em me aprofundar em fatos sobre a Bíblia para que eu possa passá-los para outras pessoas.",
  "Eu sou capaz de organizar ideias, pessoas, coisas e tempo para torná-los mais eficientes.",
  "Eu sou capaz de me relacionar com os outros emocionalmente e sou rápido em ajudar quando necessário.",
  "Fico feliz em ajudar os outros sem necessariamente ser nomeado para uma posição de liderança.",
  "Eu aceito as pessoas como elas são, sem julgá-las.",
  "Anseio por ver meus próprios pontos cegos e ajudar os outros a verem os seus também.",
  "Eu só doo quando guiado pelo Espírito Santo, verificando com Ele o quanto devo doar.",
  "Tenho prazer em fazer pesquisas para estabelecer o ensino e a doutrina corretos.",
  "Eu sou capaz de me ater aos detalhes e garantir que os planos que foram iniciados sejam realizados.",
  "Detecto facilmente falta de sinceridade ou motivações erradas.",
  "Eu gosto mais de projetos de curto prazo (1 dia - 2 semanas) do que de longo prazo (6 meses - 5 anos).",
  "Eu tomo decisões com rapidez e facilidade.",
  "Eu sou frequentemente franco, direto e não meço palavras.",
  "Eu gosto de compartilhar o que tenho com os outros para a extensão do Reino de Deus.",
  "Preocupa-me que a verdade seja apresentada de maneira clara, com atenção adequada ao significado e à exatidão das palavras.",
  "Eu gosto de supervisionar o trabalho que precisa ser feito.",
  "Evito conflitos e confrontos.",
  "Eu gosto quando os outros expressam a necessidade da minha ajuda.",
  "Tenho uma profunda preocupação em incentivar as pessoas para o crescimento espiritual.",
  "Estou consciente de ser persuasivo quando falo com as pessoas.",
  "Sinto-me profundamente comovido quando confrontado com necessidades financeiras urgentes na obra de Deus.",
  "Eu sou capaz de explicar bem como toda a Bíblia se encaixa.",
  "Sou profundamente sensível à necessidade de uma boa administração, de modo que todas as fases da atividade sejam executadas com decência e ordem.",
  "Eu pareço atrair pessoas com necessidades e problemas.",
  "Estou sempre pronto para ignorar meu próprio conforto pessoal para que as necessidades de outros sejam atendidas.",
  "Eu sou capaz de encorajar verbalmente aqueles que hesitam e estão espiritualmente perturbados.",
  "Eu sou chamado para a intercessão.",
  "Costumo mimar meus filhos e outros parentes próximos.",
  "Eu gosto de estudar a Palavra.",
  "Eu constantemente escrevo notas para mim mesmo.",
  "Eu sou um guerreiro para boas causas.",
  "Eu costumo fazer mais do que me pedem.",
  "Sempre concluo o que comecei.",
  "Eu encorajo o arrependimento que produz bons frutos.",
  "Eu sou bem sucedido em ganhar riqueza pessoal.",
  "Sou facilmente distraído por novos interesses.",
  "Eu não gosto de tarefas rotineiras.",
  "Sou alegre e bem disposto em todas as circunstâncias.",
  "Eu tenho a habilidade de fazer as pessoas se sentirem em casa.",
  "Muitas vezes preciso de uma \"caixa de ressonância\" para refletir ideias e pensamentos.",
  "Muitas vezes posso discernir o espírito e a atitude de uma pessoa.",
  "Não gosto de pedir dinheiro.",
  "Costumo verificar a fonte de conhecimento daqueles que me ensinam.",
  "Estou disposto a deixar que os outros recebam o crédito por fazer o trabalho.",
  "Não gosto de ser apressado em um trabalho ou atividade.",
  "Eu costumo ser perfeccionista.",
  "Eu espero muito de mim mesmo e dos outros.",
  "Eu desejo ser obediente a Deus - não importa o custo.",
  "Não tenho nenhum problema em confiar com alegria meus bens a outros para o trabalho do ministério.",
  "Sou mais objetivo que subjetivo.",
  "Eu prefiro iniciar um novo desafio quando algo é concluído.",
  "Costumo fazer coisas pensando nos outros.",
  "Eu tenho necessidade de me sentir apreciado.",
  "Eu gosto de esclarecer os problemas com os outros rapidamente.",
  "Eu tenho padrões morais pessoais estritos.",
  "Tenho preocupação com a questão da assistência financeira disponível para todas as áreas da obra de Deus.",
  "Sou emocionalmente autocontrolado.",
  "Eu gosto de ver uma tarefa concluída o mais rápido possível.",
  "Eu tomo cuidado com palavras e ações para evitar ferir os outros.",
  "Tenho dificuldade em dizer não aos pedidos de ajuda.",
  "Eu sou muito querido por causa da minha atitude positiva.",
  "Tenho opiniões e convicções fortes.",
  "De bom grado doo tempo, energia, posses, amor e dinheiro ao trabalho do Senhor.",
  "Eu resolvo problemas a partir de princípios das Escrituras.",
  "Eu gosto de trabalhar com pessoas e de estar perto de pessoas.",
  "Sou motivado para ajudar as pessoas a terem relacionamentos corretos umas com as outras.",
  "Eu mantenho tudo meticulosamente ordem.",
  "Se eu estiver aconselhando e não vir nenhum esforço da pessoa para mudar, paro.",
  "Eu costumo ser introspectivo.",
  "Dou mais de 10% da minha renda.",
  "Sinto que o estudo da Bíblia é fundamental para a operação de todos os dons.",
  "Não tenho nenhum problema em estar sob autoridade para exercer autoridade.",
  "Eu tomo medidas para aliviar a aflição e remover mágoas dos outros.",
  "Eu gosto de projetos e trabalhos manuais.",
  "Sou fluente em comunicação.",
  "Eu acredito que a Bíblia é a base para a verdade, a confiança, a ação e a autoridade.",
  "Eu amo doar sem que os outros saibam sobre isso.",
  "Tenho fortes convicções e opiniões baseadas na investigação de fatos.",
  "Normalmente não assumo responsabilidades, a menos que sejam delegadas a mim por aqueles que estão em posição de autoridade.",
  "Eu posso perceber a atmosfera espiritual e emocional de uma pessoa ou de um grupo.",
  "Eu sou uma pessoa detalhista e tenho uma boa memória.",
  "Eu me concentro em trabalhar com pessoas.",
  "Sou ousado quando atuo em princípios espirituais.",
  "Eu intercedo pelas necessidades das pessoas e pela salvação das almas.",
  "É importante que a verdade seja estabelecida em todas as situações.",
  "Assumirei a responsabilidade se não houver uma liderança específica.",
  "Eu tenho a tendência de ser inclusivo.",
  "Eu mostro mais amor em ações e atitudes do que em palavras.",
  "Eu gosto de ter uma resposta visível ao falar com as pessoas.",
  "Eu faço tudo que posso para promover o crescimento espiritual das pessoas.",
  "Eu não sou ingênuo.",
  "Eu sou perspicaz.",
  "Eu sofro críticas a fim de fazer o trabalho.",
  "Sou facilmente ferido pelos outros.",
  "Costumo criticar pessoas que não ajudam com necessidades óbvias.",
  "Uso as Escrituras fora de contexto para apresentar um ponto.",
  "Eu costumo ser crítico e contundente.",
  "Eu tenho uma habilidade natural e eficaz para negócios.",
  "Acredito que a verdade tem o poder intrínseco de produzir mudanças.",
  "Tenho que tomar cuidado para não usar as pessoas para fazer o trabalho.",
  "Minha natureza afetuosa é muitas vezes mal interpretada pelo sexo oposto.",
  "Acho difícil aceitar ser servido por outros.",
  "Eu sou sincero e tenho opiniões fortes.",
  "Eu posso ser intolerante com opiniões e pontos de vista diferentes dos meus.",
  "Eu me ofereço rapidamente para ajudar onde há necessidade.",
  "Eu não aceito os pontos de vista dos outros muito rapidamente.",
  "Eu tenho tendência a guiar a mim mesmo e negligenciar minhas necessidades pessoais e familiares.",
  "Tenho propensão a tomar para mim a ofensa feita a outra pessoa.",
  "Eu me magoo facilmente quando sou menosprezado.",
  "Eu posso ficar excessivamente autoconfiante.",
  "Eu luto com problemas de autoimagem.",
];